name: deploy to GitHub Pages And upload to Algolia

on:
  # after every push to master
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Clear old index in Algolia
        uses: algolia/algoliasearch-action@v1
        with:
          application_id: UUU68T8E14
          api_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          action: clear-index
          index_name: hugo

      - name: Upload to Algolia
        # You may pin to the exact commit or the version.
        # uses: wangchucheng/algolia-uploader@2146c50bde2441041f9727c2b89accebcc998c74
        uses: wangchucheng/algolia-uploader@v0.1.0
        with:
          # Application ID of Algolia
          app_id: UUU68T8E14
          # Admin API Key of Algolia
          admin_key: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          # Index name of Algolia
          index_name: hugo
          # Index file path
          index_file_path: public/index.json
